### ISSUE TITLE
Update zenlink currency conversion for Amplitude and Pendulum

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#201]
We need to update the '[zenlink_id_to_currency_id](https://github.com/pendulum-chain/pendulum/blob/1dbf5375e961c0fd52eac67ed13ccccab61de821/runtime/foucoco/src/zenlink.rs#L127-L147)' function to something that can also derive our Spacewalk currencies (as we also want to use Spacewalk/Stellar assets on Zenlink).

Now when we define the [conversion from a zenlink to a local currency ID](https://github.com/pendulum-chain/pendulum/blob/1dbf5375e961c0fd52eac67ed13ccccab61de821/runtime/foucoco/src/zenlink.rs#L127-L147), right now we always assume the provided asset_index to be the XCM index. But we somehow have to link to our Stellar assets in this conversion function because we have to be able to derive it from the ZenlinkAssetId.
Since the asset_index is of type `u64` but the XCM index we use in our CurrencyId can only be `u8` I'd say it's safe to start assigning Stellar assets with 256 (because u8 only ranges from 0-255)

```
match asset_id.asset_type {
		NATIVE => Ok(CurrencyId::Native),
		LOCAL => {
			let foreign_id: u8 = asset_id.asset_index.try_into().map_err(|_| {
				log::error!("{} has no Foreign Currency Id match.", asset_id.asset_index);
				()
			})?;

            if foreign_id <= u8::MAX {
			    Ok(XCM(foreign_id))
            } else {
               // TODO add some hard-coded lookup
               match foreign_id {
                    256 => Stellar::StellarNative,
                    257 => yadda yadda ....
                    _ => None
            }
		},
		other => {
			log::error!("Unsupported asset type index:{other}");
			Err(())
		},
	}
```

**Comment by TorstenStueber** [comment]
@ebma makes sense. What currencies shall we encode right now? (also @vadaynujra)

**Comment by vadaynujra** [comment]
The ones in [this](https://github.com/pendulum-chain/spacewalk/issues/311) ticket are enough for now.

**Comment by vadaynujra** [comment]
@ebma is this ticket ready to be worked on and is relevant for the current Zenlink work?

**Comment by ebma** [comment]
Because ticket #241 is probably getting rid of a function mentioned in this ticket, I now marked this ticket as blocked by #241 and we should wait for the outcome of that ticket. This ticket might not be necessary afterward.

**Comment by adelarja** [comment]
After reading this issue, I realized that I need to make a minor change in [this PR](https://github.com/pendulum-chain/spacewalk/pull/359).

I believe that implementing a hard-coded lookup is the best approach for converting ZenlinkAsset to StellarAsset. I was trying to figure out how we could convert Stellar assets to ZenlinkAssets using the StellarAsset code (and vice versa), but it's challenging because the StellarAsset code ranges from 32 to 96 bits (4 to 12 bytes), while the ZenlinkAsset index is a u64 (8 bytes) value. This could cause difficulties when generating a pool with a Stellar asset.

However, I didn't consider the possibility of creating a pool with Stellar assets. In such cases, the `ZenlinkLPToken(u8, u8)` enum value won't be sufficient since we can't distinguish between Stellar and XCM tokens using u8 ID values.

We have two options to address this:

1. Change the enum value from `ZenlinkLPToken(u8, u8)` to `ZenlinkLPToken(u16, u16)`.
2. Change the enum value from `ZenlinkLPToken(u8, u8)` to `ZenlinkLPToken(u8, u8, u8, u8)`. In this case, two of the u8 values represent the token IDs, while the other two represent the token types used in the pool (e.g., 0 for XCM tokens, 1 for Stellar tokens, etc.).

In both cases, the bitwise operations remain similar to implement.

In the first case:

```rust
let lp_token_index: u64 = (discriminant << 8) + (token1_id << 16) + (token2_id << 32);

// Reverse operations:
let discriminant: u8 = (lp_token_index & 0x0000_0000_0000_ff00) >> 8;
let token1_id: u16 = (lp_token_index & 0x0000_0000_ffff_0000) >> 16;
let token2_id: u16 = (lp_token_index & 0x0000_ffff_0000_0000) >> 32;
```

We can use the discriminant to determine if the index represents an lp_token, XCM token, or Stellar token. Additionally, we can identify whether a token is an XCM token or Stellar token based on its token ID value (0-255 for XCM, greater than 255 for Stellar tokens). If the asset index is for a non-lp_token, the index directly represents the token ID (greater than 255 indicates a Stellar token, while others indicate an XCM token).

In the second case, we have a similar approach:

```rust
let lp_token_index: u64 = (discriminant << 8) + (token1_id << 16) + (token1_type << 24) + (token2_id << 32) + (token2_type << 40);

// Reverse operations:
let discriminant: u8 = (lp_token_index & 0x0000_0000_0000_ff00) >> 8;
let token1_id: u8 = (lp_token_index & 0x0000_0000_00ff_0000) >> 16;
let token1_type: u8 = (lp_token_index & 0x0000_0000_ff00_0000) >> 20;
let token2_id: u8 = (lp_token_index & 0x0000_00ff_0000_0000) >> 32;
let token2_type: u8 = (lp_token_index & 0x0000_ff00_0000_0000) >> 40;
```

This approach allows us to determine if the index represents an lp_token, XCM token, or Stellar token using the discriminant. Furthermore, with the token_type, we can identify if the token represents an XCM or Stellar token. If the asset index is for a non-lp_token, the index directly represents the token ID. By setting different discriminant values, we can determine the type of token it represents.

These changes will enable us to handle both XCM and Stellar assets effectively.

**Comment by TorstenStueber** [comment]
What are the possible values of the `discriminant`?

**Comment by adelarja** [comment]
I believe we need to define one discriminant value per CurrencyId. This approach is similar to what Bifrost is implementing [here](https://github.com/bifrost-finance/bifrost/blob/develop/node/primitives/src/currency.rs#L415).

**Comment by TorstenStueber** [comment]
Their `CurrencyId` is a big enum, so is ours. Their discriminator is the variant of this enum but does that really make sense for us? Isn't that actually specified through the `token1_type` and `token2_type` [as you wrote above](https://github.com/pendulum-chain/pendulum/issues/201#issuecomment-1589883661)? (maybe also @ebma).

**Comment by ebma** [comment]
Since our `CurrencyId` is a little nested, we could do something like this maybe?
```
pub fn discriminant(&self) -> u8 {
		match *self {
			Self::Native(..) => 0,
			Self::XCM(..) => 1,
			Self::Stellar(Asset) => match Asset {
                                StellarNative = 2,
                         	AlphaNum4 { .. } => 3,
                          	AlphaNum12 { .. } => 4,
                         },
                        Self::ZenlinkLPToken(..) => 5,
		}
	}
```

@TorstenStueber I think we actually really need the `discriminant` because without it we could not be 100% sure what we are dealing with. Let's say we are facing a Zenlink asset_index (`u64`).  Now we are doing the bit-shifting to split the `u64` into the sub-parts. With the discriminant, we immediately know which type of `CurrencyId` we are facing.  Without it, we might face rare circumstances where we can't know. For example, if we happen to have an `asset_index` that when split into sub-parts yields only `0` values for `token1_type`, `token1_id`, `token2_type`, `token2_id`. How would we know if this is supposed to be our native token or some LP token combining our native token and something else?

**Comment by TorstenStueber** [comment]
Is the discriminant just another word for the 2nd least significant byte of the `u64` ZenlinkAsset?

**Comment by adelarja** [comment]
Exactly, the discriminant is the 2nd least significant byte of the ZenlinkAsset index shifted 8 bits to the right.

In [this comment](https://github.com/pendulum-chain/pendulum/issues/201#issuecomment-1589883661) I only talked about the ZenlinkLPToken discriminant, sorry about that.

When we create a ZenlinkToken, the discriminant will be part of the index.

We could obtain the discriminant depending on the CurrencyId (this function should be a method of CurrencyId, like Bifrost does) :

```rust
fn discriminant(currency: &CurrencyId) -> u8 {
	match currency {
		CurrencyId::Native => 0,
		CurrencyId::XCM(_) => 1,
		CurrencyId::Stellar(_) => 2,
		CurrencyId::ZenlinkLPToken(_, _, _, _) => 6,
	}
}
```

This would be examples of ZenlinkAsset indexes:

```rust
// Native ZenlinkAsset index
0x0000_0000_0000_0000

// XCM ZenlinkAsset index (discriminant 1). index = (disc << 8) + (token_id)
0x0000_0000_0000_0100 // XCM(0) token index
0x0000_0000_0000_0101 // XCM(1) token index
0x0000_0000_0000_0102 // XCM(2) token index

// Stellar ZenlinkAsset index (discriminant 2). index = (disc << 8) + (hardcoded_token_id)
0x0000_0000_0000_0200 // Stellar USDC hardcoded index
0x0000_0000_0000_0201 // Stellar TZS hardcoded index
0x0000_0000_0000_0202 // Stellar BRL hardcoded index
0x0000_0000_0000_0203 // Stellar XLM hardcoded index

// ZenlinkLPToken index (discriminant 6). index = (disc << 8) + (token1_id << 16) + (token1_disc << 24) + (token2_id << 32) + (token2_disc << 40)
0x0000_0101_0100_0600 // ZenlinkLPToken for XCM(0) and XCM(1) pair.
0x0000_0200_0100_0600 // ZenlinkLPToken for XCM(0) and Stellar USDC pair.
0x0000_0201_0200_0600 // ZenlinkLPToken for Stellar USDC and Stellar TZS pair.

```

From this indexes, we would be able to convert from ZenlinkAssetId to CurrencyId (and vice versa), because we have all the information we need to do that.

[Here](https://github.com/pendulum-chain/pendulum/blob/c003c2bd929352b28c90da6390b6184f76c745d9/runtime/foucoco/src/zenlink.rs#LL140C1-L217C2) is a draft of the conversion functions. I added some hard-coded values for the Stellar assets and implemented the draft of the logic.

BTW, when writing the previous draft, I found another doubt. In order to create a stellar Asset, we need the issuer information. Should we hard-code this info too?

In case there are more than one issuer for the same token (i.e USDC), we could have different ids. Something like:

```rust
// Stellar ZenlinkAsset index (discriminant 2)
0x0000_0000_0000_0200 // Stellar USDC hardcoded index for issuer 1
0x0000_0000_0000_0201 // Stellar USDC hardcoded index for issuer 2
```

**Comment by TorstenStueber** [comment]
Okay, makes a lot of sense, understood.

Regarding Stellar asset: out of the whole big space of Stellar assets we would need hand pick assets that we want to support for Zenlink as we can only pick 256 different Stellar assets here (correct?). There is only [one official USDC](https://stellar.expert/explorer/public/asset/USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN) on Stellar (there is a particular issuer for this – centre.io, whose address is `GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN`).

Similar for other Stellar assets. They would then be assigned numbers 0 to 255 via our conversion function.

**Comment by ebma** [comment]
Yes, the issuer of our supported assets would have to be 'hard-coded' if you will. We will always only support exactly one USDC, one BRL, etc. so it should not be a problem.

**Comment by ebma** [comment]
This ticket can be closed since the changes were added as part of [this](https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/pendulum/246) PR.
