### ISSUE TITLE
Improve error handling in chain extension

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#250]
At the moment, we throw a lot of `DispatchError::Other()` errors in our chain extension. 
When a smart contract calls our chain extension and such an error is shown, the whole execution traps and no error message is shown (because although `DispatchError::Other()` contains a message, this messages is stripped).
What we should do instead is, to create an error enum (like [this](https://github.com/AstarNetwork/Astar/blob/master/chain-extensions/types/dapps-staking/src/lib.rs)) and in case we encounter an error in our chain extension function, instead of aborting with a `DispatchError`, we encode the respective error (like [this](https://github.com/AstarNetwork/Astar/blob/51873938c8d63cc87885db95af74cfb3ec36d015/chain-extensions/dapps-staking/src/lib.rs#L249)) and send it back to our smart contract, which is then able to show a proper error message based on that index.

This would improve the developer experience, because, at the moment you don't see what exactly failed about your contract call.

**Comment by ebma** [comment]
The problem here is that, apparently Error enums should be defined in pallets in order to be usable in the runtime. Otherwise, we can only really use the `DispatchError`. Maybe we need to create some extra pallet just for that purpose.

**Comment by TorstenStueber** [comment]
If we avoided to introduce an extra pallet for this, then we would possibly need to implement something similar. The `pallet` macros automatically implement an implementation of `From<Error<T>>` for `DispatchError`, where `Error<T>` is the error type defined in the pallet. It creates something like this:

```
    DispatchError::Module(ModuleError {
      index: // the the index of the pallet defined in the runtime
      error: // the SCALE encoding of the error extended to frame_support::MAX_MODULE_ERROR_ENCODED_SIZE,
      message: // the doc comment of the error,
    })
```

Since the index indicates that this should only be used for pallet errors, I think that we would have to introduce a new pallet if we want to create a `ModuleError`.

Astar uses a different approach, at least for their [Dapp Staking chain extension](https://github.com/AstarNetwork/Astar/blob/master/chain-extensions/dapps-staking/src/lib.rs#L83). They only ever return `DispatchError`s when any of the environment functions returns an error (which is already a `DispatchError`), e.g., [here](https://github.com/AstarNetwork/Astar/blob/14d73c5b7303928be07dee1ac896ea52c2594f0f/chain-extensions/dapps-staking/src/lib.rs#L115C18-L115C18).

For errors generated in their own code, they don't return a `DispatchError` but an `Ok` of a `RetVal::Converging` and then they define different error codes for `Converging` (whereas we only ever use 0 for success). See [an example](https://github.com/AstarNetwork/Astar/blob/14d73c5b7303928be07dee1ac896ea52c2594f0f/chain-extensions/dapps-staking/src/lib.rs#L227C32-L227C32) and the definition of the [error codes](https://github.com/AstarNetwork/Astar/blob/14d73c5b7303928be07dee1ac896ea52c2594f0f/chain-extensions/types/dapps-staking/src/lib.rs#L26-L87).

**Comment by ebma** [comment]
I'd opt for the alternative approach then since it is similar to what I described in the ticket. 
I think creating a `ModuleError` would be hacky since the `ModuleError` is probably specifically for pallets and we wouldn't be using it in a pallet then.

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/250?planning-poker) with Zenhub @ashneverdawn @TorstenStueber
