### ISSUE TITLE
Deploy runtime upgrade for DEV token on Moonbeam Foucoco node

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#369]
We need to deploy the runtime upgrade that adds support for the DEV token (added in https://github.com/pendulum-chain/pendulum/issues/366) to our Moonbeam Foucoco node.

## TODO
- Bump spec version
- Compile and deploy runtime upgrade on Moonbeam Foucoco node

**Comment by bogdanS98** [comment]
Runtime upgrade for Moonbeam Foucoco is live and producing blocks since December 21st 2023.
Changes included:
- Registration of DEV token
- XCM config changes regarding currency conversion of DEV token (this change is present only in Moonbeam Foucoco, but NOT on Foucoco yet - ticket for Foucoco [here](https://github.com/pendulum-chain/pendulum/issues/387))
This does NOT include integration test for transferring DEV token since that issue is closed now (see description [here](https://github.com/pendulum-chain/pendulum/issues/371#issue-2031307415))

WASM file used for the upgrade:
[foucoco_runtime.compact.compressed.wasm.zip](https://github.com/pendulum-chain/pendulum/files/13812251/foucoco_runtime.compact.compressed.wasm.zip)

**Comment by prayagd** [comment]
@bogdanS98 Can you please add an estimate to this one?
